set nocompatible
syntax on

" indenting
set autoindent
set smartindent
set tabstop=3
set shiftwidth=3
set expandtab

" row numbers
set number
" highlights matching braces 
set showmatch

" intelligent comments
set comments=s1:/*,mb:\ *,elx:\ */


nnoremap w k
nnoremap s j
nnoremap a h
nnoremap d l

" saves with F2
nmap <F2> :w<CR>
imap <F2> <F2><ESC>:w<CR>i




